Repository grpc-ecosystem/grpc-spring, pull requests merged in 2018-12, with the labels that each got.

#145 Automatically create actuator InfoContributor
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/package-info.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metric/package-info.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/autoconfigure/package-info.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/metric/MetricUtils.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/metric/package-info.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/GrpcUtils.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/package-info.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerMetricAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/package-info.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/package-info.java
Labels: enhancement

#148 Added tests for streaming calls
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/authentication/AnonymousAuthenticationReader.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/AccessPredicate.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/AccessPredicates.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/ManualGrpcSecurityMetadataSource.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/AuthenticatingServerInterceptor.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/AuthorizationCheckingServerInterceptor.java
  tests/src/test/java/net/devh/boot/grpc/test/config/ManualSecurityConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/config/WithBasicAuthSecurityConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/security/AbstractSecurityTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/AbstractSecurityWithBasicAuthTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/AnnotatedSecurityWithCertificateTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/ConcurrentSecurityTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/ManualSecurityWithCertificateTest.java
  tests/src/test/java/net/devh/boot/grpc/test/server/TestServiceImpl.java
  tests/src/test/java/net/devh/boot/grpc/test/util/DynamicTestCollection.java
  tests/src/test/java/net/devh/boot/grpc/test/util/FutureAssertions.java
  tests/src/test/java/net/devh/boot/grpc/test/util/GrpcAssertions.java
  tests/src/test/java/net/devh/boot/grpc/test/util/TriConsumer.java
  tests/src/test/proto/TestService.proto
Labels: enhancement

#152 Support java 11 compile
  .travis.yml
  build.gradle
  examples/grpc-lib/build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  grpc-client-spring-boot-autoconfigure/build.gradle
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClient.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
  tests/build.gradle
Labels: enhancement

#155 Fix most compile time warnings
  build.gradle
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/AbstractChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/GrpcChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
  grpc-server-spring-boot-autoconfigure/build.gradle
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/authentication/AnonymousAuthenticationReader.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/AccessPredicates.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/GrpcServerLifecycle.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/service/AnnotationGrpcServiceDiscoverer.java
Labels: enhancement

#158 Fixes initialization order issues causing NPEs in `@PostConstruct`
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClient.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
  tests/src/test/java/net/devh/boot/grpc/test/AbstractSimpleServerClientTest.java
  tests/src/test/java/net/devh/boot/grpc/test/inject/GrpcClientInjectionTest.java
Labels: bug, enhancement

#154 Update to grpc 1.17.0
  build.gradle
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientAutoConfiguration.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/AddressChannelNameResolver.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
Labels: enhancement

#160 Add call attributes to the authentication if no details are present
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/AuthenticatingServerInterceptor.java
Labels: enhancement

#165 Fix link to common javadoc
  README.md
Labels: bug
