Repository grpc-ecosystem/grpc-spring, pull requests merged in 2019-07, with the labels that each got.

#246 Support password encoded private keys
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/NettyChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/ShadedNettyChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/NettyGrpcServerFactory.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/ShadedNettyGrpcServerFactory.java
Labels: enhancement

#242 Update spring dependencies
  build.gradle
  deploy.gradle
  examples/cloud-eureka-server/build.gradle
  examples/cloud-grpc-client/build.gradle
  examples/cloud-grpc-server/build.gradle
  gradle/wrapper/gradle-wrapper.properties
  grpc-client-spring-boot-autoconfigure/build.gradle
  grpc-common-spring-boot/build.gradle
  grpc-server-spring-boot-autoconfigure/build.gradle
  testExamples.sh
  tests/build.gradle
Labels: cleanup, documentation, enhancement

#250 Split AuthenticatingServerInterceptor into an interface
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerSecurityAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/AbstractAuthenticatingServerCallListener.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/AuthenticatingServerInterceptor.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/DefaultAuthenticatingServerInterceptor.java
Labels: enhancement

#254 Properly use @ConditionalOnProperty
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerFactoryAutoConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/InterAndInProcessSetup2Test.java
Labels: bug

#241 Update DiscoveryClientNameResolver implementation
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientResolverFactory.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/GrpcUtils.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataEurekaConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataNacosConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/cloud/ConsulGrpcRegistrationCustomizer.java
Labels: bug, enhancement

#255 Update GRPC Version
  build.gradle
Labels: enhancement

#259 Implement grpcRequest scope
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/scope/GrpcRequestScope.java
  tests/src/test/java/net/devh/boot/grpc/test/config/ScopedServiceConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/interceptor/DefaultServerInterceptorTest.java
  tests/src/test/java/net/devh/boot/grpc/test/scope/GrpcRequestScopeTest.java
  tests/src/test/java/net/devh/boot/grpc/test/server/ScopedTestServiceImpl.java
Labels: enhancement
