Repository grpc-ecosystem/grpc-spring, pull requests merged in 2019-04, with the labels that each got.

#208 Make GrpcServerSecurityAutoConfiguration a proper auto configuration
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerSecurityAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  tests/src/test/java/net/devh/boot/grpc/test/config/BaseAutoConfiguration.java
Labels: bug, enhancement

#209 Update spring libraries
  build.gradle
Labels: enhancement

#215 Consider ordering while registering Server/Client Interceptors
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/interceptor/AnnotationGlobalClientInterceptorConfigurer.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/interceptor/AnnotationGlobalServerInterceptorConfigurer.java
  tests/src/test/java/net/devh/boot/grpc/test/config/OrderedClientInterceptorConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/config/OrderedServerInterceptorConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/interceptor/OrderedClientInterceptorTest.java
  tests/src/test/java/net/devh/boot/grpc/test/interceptor/OrderedServerInterceptorTest.java
Labels: enhancement

#218 Fix wrong BeanPostProcessor bean definition
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientAutoConfiguration.java
Labels: bug, enhancement

#219 Fix formatting and warnings
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/AbstractChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelsProperties.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/interceptor/GlobalClientInterceptorConfigurer.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/interceptor/GlobalServerInterceptorConfigurer.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/ManualGrpcSecurityMetadataSource.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/service/GrpcServiceDiscoverer.java
  tests/src/test/java/net/devh/boot/grpc/test/config/OrderedClientInterceptorConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/config/OrderedServerInterceptorConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/interceptor/OrderedClientInterceptorTest.java
  tests/src/test/java/net/devh/boot/grpc/test/interceptor/OrderedServerInterceptorTest.java
Labels: cleanup

#220 Remove deprecated AuthenticatingClientInterceptors
  README-zh.md
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/security/AuthenticatingClientInterceptors.java
  tests/src/test/java/net/devh/boot/grpc/test/config/InProcessConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/config/WithBasicAuthSecurityConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/security/AbstractSecurityTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/AbstractSecurityWithBasicAuthTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/AnnotatedSecurityWithBasicAuthTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/ConcurrentSecurityTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/ManualSecurityWithBasicAuthTest.java
Labels: cleanup, enhancement

#217 Update grpc java to 1.20
  build.gradle
  examples/grpc-lib/build.gradle
  grpc-client-spring-boot-autoconfigure/build.gradle
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientAutoConfiguration.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/NettyChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/ShadedNettyChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClient.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/CompositeNameResolverFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/ConfigMappedNameResolverFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientResolverFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/NameResolverConstants.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/StaticNameResolverProvider.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/security/CallCredentialsHelper.java
  grpc-common-spring-boot/build.gradle
  grpc-server-spring-boot-autoconfigure/build.gradle
  tests/build.gradle
Labels: enhancement

#221 Add some additional/missing javadocs and toString() methods to client security
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/security/CallCredentialsHelper.java
  tests/src/test/java/net/devh/boot/grpc/test/security/ConcurrentSecurityTest.java
Labels: documentation, enhancement

#222 Adds simultaneous support for in- and inter-process channels/servers
  README-zh.md
  README.md
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientAutoConfiguration.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/InProcessOrAlternativeChannelFactory.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerFactoryAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/InProcessGrpcServerFactory.java
  grpc-server-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  tests/src/test/java/net/devh/boot/grpc/test/InterAndInProcessSetupTest.java
  tests/src/test/java/net/devh/boot/grpc/test/config/BaseAutoConfiguration.java
Labels: enhancement
