Repository grpc-ecosystem/grpc-spring, pull requests merged in 2019-09, with the labels that each got.

#279 Update dependencies
  build.gradle
  examples/security-grpc-bearerAuth-server/build.gradle
  examples/security-grpc-bearerAuth-server/src/main/java/net/devh/boot/grpc/examples/security/server/SecurityConfiguration.java
  grpc-server-spring-boot-autoconfigure/build.gradle
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataNacosConfiguration.java
Labels: enhancement

#280 Drop support for grpc versions prior to 1.21.0 and use grpc's NameResolverRegistry
  README.md
  docs/en/client/configuration.md
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientAutoConfiguration.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcDiscoveryClientAutoConfiguration.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelsProperties.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/CompositeNameResolverFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/ConfigMappedNameResolverFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientResolverFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/StaticNameResolverProvider.java
  tests/src/test/java/net/devh/boot/grpc/test/codec/BeanCodecTest.java
  tests/src/test/java/net/devh/boot/grpc/test/codec/CustomCodecTest.java
  tests/src/test/java/net/devh/boot/grpc/test/codec/GzipCodecTest.java
  tests/src/test/java/net/devh/boot/grpc/test/codec/IdentityCodecTest.java
  tests/src/test/java/net/devh/boot/grpc/test/metric/MetricCollectingInterceptorTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/AnnotatedSecurityWithCertificateTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/LegacyAnnotatedSecurityWithCertificateTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/LegacyManualSecurityWithCertificateTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/ManualSecurityWithCertificateTest.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/CustomCiphersAndProtocolsSetupTest.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/NameResolverConnectionTest.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/PlaintextSetupTest.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/SelfSignedMutualSetupTest.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/SelfSignedServerSetupTest.java
Labels: enhancement, incompatibility

#281 Update Javadoc Task options
  build.gradle
Labels: documentation

#283 Add support for connecting to the own server
  docs/en/client/configuration.md
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientAutoConfiguration.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientResolverFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/NameResolverRegistration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/nameresolver/SelfNameResolver.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/nameresolver/SelfNameResolverFactory.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/nameresolver/package-info.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/SelfNameResolverConnectionTest.java
Labels: enhancement

#284 Rename "cloud" package name part of local example to "local"
  examples/local-grpc-client/src/main/java/net/devh/boot/grpc/examples/local/client/GlobalClientInterceptorConfiguration.java
  examples/local-grpc-client/src/main/java/net/devh/boot/grpc/examples/local/client/GrpcClientController.java
  examples/local-grpc-client/src/main/java/net/devh/boot/grpc/examples/local/client/GrpcClientService.java
  examples/local-grpc-client/src/main/java/net/devh/boot/grpc/examples/local/client/LocalGrpcClientApplication.java
  examples/local-grpc-client/src/main/java/net/devh/boot/grpc/examples/local/client/LogGrpcInterceptor.java
  examples/local-grpc-server/src/main/java/net/devh/boot/grpc/examples/local/server/GlobalInterceptorConfiguration.java
  examples/local-grpc-server/src/main/java/net/devh/boot/grpc/examples/local/server/GrpcServerService.java
  examples/local-grpc-server/src/main/java/net/devh/boot/grpc/examples/local/server/LocalGrpcServerApplication.java
  examples/local-grpc-server/src/main/java/net/devh/boot/grpc/examples/local/server/LogGrpcInterceptor.java
Labels: cleanup

#285 Expose channel connectivity to actuator
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientHealthAutoConfiguration.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientMetricAutoConfiguration.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/AbstractChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/GrpcChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/InProcessOrAlternativeChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
Labels: enhancement
