Repository grpc-ecosystem/grpc-spring, pull requests merged in 2020-03, with the labels that each got.

#333 Gradle and Protobuf Gradle Updates
  .gitattributes
  README.md
  build.gradle
  deploy.gradle
  examples/cloud-eureka-server/build.gradle
  examples/cloud-grpc-client/build.gradle
  examples/cloud-grpc-server/build.gradle
  examples/grpc-lib/build.gradle
  examples/local-grpc-client/build.gradle
  examples/local-grpc-server/build.gradle
  examples/security-grpc-bearerAuth-client/build.gradle
  examples/security-grpc-bearerAuth-server/build.gradle
  examples/security-grpc-client/build.gradle
  examples/security-grpc-server/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  grpc-client-spring-boot-autoconfigure/build.gradle
  grpc-client-spring-boot-starter/build.gradle
  grpc-common-spring-boot/build.gradle
  grpc-server-spring-boot-autoconfigure/build.gradle
  grpc-server-spring-boot-starter/build.gradle
  testExamples.sh
  tests/build.gradle
Labels: cleanup, enhancement

#337 Add cross references to the client docs
  docs/en/client/configuration.md
  docs/en/client/getting-started.md
Labels: documentation

#343 Update dependencies
  build.gradle
  docs/en/versions.md
  examples/grpc-lib/build.gradle
  tests/build.gradle
Labels: enhancement
