Repository grpc-ecosystem/grpc-spring, pull requests merged in 2021-01, with the labels that each got.

#465 grpc exception handling
  docs/en/index.md
  docs/en/server/configuration.md
  docs/en/server/contextual-data.md
  docs/en/server/exception-handling.md
  docs/en/server/getting-started.md
  docs/en/server/security.md
  docs/en/server/testing.md
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/advice/GrpcAdvice.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/advice/GrpcAdviceDiscoverer.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/advice/GrpcAdviceExceptionHandler.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/advice/GrpcAdviceExceptionInterceptor.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/advice/GrpcAdviceExceptionListener.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/advice/GrpcAdviceIsPresentCondition.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/advice/GrpcExceptionHandler.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/advice/GrpcExceptionHandlerMethodResolver.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcAdviceAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  grpc-server-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/server/advice/GrpcAdviceDiscovererTest.java
  tests/src/test/java/net/devh/boot/grpc/test/advice/AbstractSimpleServerClientTest.java
  tests/src/test/java/net/devh/boot/grpc/test/advice/AdviceExceptionHandlingTest.java
  tests/src/test/java/net/devh/boot/grpc/test/advice/AdviceIsPresentAutoConfigurationTest.java
  tests/src/test/java/net/devh/boot/grpc/test/advice/AdviceNotPresentAutoConfigurationTest.java
  tests/src/test/java/net/devh/boot/grpc/test/advice/GrpcMetaDataUtils.java
  tests/src/test/java/net/devh/boot/grpc/test/config/GrpcAdviceConfig.java
  tests/src/test/java/net/devh/boot/grpc/test/util/LoggerTestUtil.java
Labels: documentation, enhancement

#479 Improve server getting-started docs
  docs/en/server/getting-started.md
Labels: documentation

#485 exception handling - best match
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/advice/GrpcExceptionHandlerMethodResolver.java
  tests/src/test/java/net/devh/boot/grpc/test/advice/AdviceExceptionHandlingTest.java
  tests/src/test/java/net/devh/boot/grpc/test/advice/AdviceIsPresentAutoConfigurationTest.java
  tests/src/test/java/net/devh/boot/grpc/test/config/GrpcAdviceConfig.java
Labels: enhancement
