Repository grpc-ecosystem/grpc-spring, pull requests merged in 2021-11, with the labels that each got.

#596 Add dynamic CallCredentials helpers
  docs/en/client/security.md
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/security/CallCredentialsHelper.java
Labels: enhancement

#595 Update and move compatibility info to version documentation
  README.md
  docs/en/versions.md
Labels: documentation

#594 Improve authentication capabilities
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/authentication/GrpcAuthenticationReader.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/AuthenticatingServerInterceptor.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/DefaultAuthenticatingServerInterceptor.java
  tests/src/test/java/net/devh/boot/grpc/test/interceptor/DefaultServerInterceptorTest.java
  tests/src/test/java/net/devh/boot/grpc/test/server/TestServiceImpl.java
Labels: enhancement

#600 Improve DiscoveryClientNameResolver implementation
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientResolverFactory.java
Labels: enhancement

#598 Update dependencies and plugins
  build.gradle
  docs/en/versions.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: enhancement

#520 Java 16 + gradle 7.0 compatibility
  build.gradle
Labels: enhancement

#609 Update the getting started documentation
  docs/en/client/getting-started.md
  docs/en/server/getting-started.md
Labels: documentation

#606 Mention grpcChannel health indicator in docs
  docs/en/client/configuration.md
Labels: documentation

#605 Add keystore support
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/NettyChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/ShadedNettyChannelFactory.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/config/GrpcChannelProperties.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/security/KeyStoreUtils.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/NettyGrpcServerFactory.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/ShadedNettyGrpcServerFactory.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/SelfSignedMutualKeystoreSetupTest.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/SelfSignedServerKeystoreSetupTest.java
  tests/src/test/resources/certificates/client1.p12
  tests/src/test/resources/certificates/client2.p12
  tests/src/test/resources/certificates/generateCertificates.sh
  tests/src/test/resources/certificates/server.p12
  tests/src/test/resources/certificates/trusted-clients.p12
  tests/src/test/resources/certificates/trusted-servers.p12
Labels: enhancement

#608 Add grpc server lifecycle events
  docs/en/index.md
  docs/en/server/configuration.md
  docs/en/server/contextual-data.md
  docs/en/server/events.md
  docs/en/server/exception-handling.md
  docs/en/server/getting-started.md
  docs/en/server/security.md
  docs/en/server/testing.md
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerFactoryAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/event/GrpcServerLifecycleEvent.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/event/GrpcServerShutdownEvent.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/event/GrpcServerStartedEvent.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/event/GrpcServerTerminatedEvent.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/event/package-info.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/GrpcServerLifecycle.java
  grpc-server-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/server/serverfactory/GrpcServerLifecycleTest.java
  tests/src/test/java/net/devh/boot/grpc/test/shutdown/GrpcServerLifecycleWithCallsTest.java
Labels: enhancement, documentation

#610 Update to spring-boot 2.5.7
  build.gradle
  docs/en/versions.md
Labels: enhancement
