Repository grpc-ecosystem/grpc-spring, pull requests merged in 2021-04, with the labels that each got.

#521 Upgrade dependencies to the latest versions
  build.gradle
  docs/en/versions.md
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#504 Add nacos example
  build.gradle
  docs/zh-CN/examples.md
  examples/cloud-grpc-client-nacos/build.gradle
  examples/cloud-grpc-client-nacos/src/main/java/net/devh/boot/grpc/examples/cloud/client/CloudGrpcNacosClientApplication.java
  examples/cloud-grpc-client-nacos/src/main/java/net/devh/boot/grpc/examples/cloud/client/GrpcClientController.java
  examples/cloud-grpc-client-nacos/src/main/java/net/devh/boot/grpc/examples/cloud/client/GrpcClientService.java
  examples/cloud-grpc-client-nacos/src/main/resources/application.yml
  examples/cloud-grpc-server-nacos/build.gradle
  examples/cloud-grpc-server-nacos/src/main/java/net/devh/boot/grpc/examples/cloud/server/CloudGrpcNacosServerApplication.java
  examples/cloud-grpc-server-nacos/src/main/java/net/devh/boot/grpc/examples/cloud/server/GrpcServerService.java
  examples/cloud-grpc-server-nacos/src/main/resources/application.yml
  grpc-server-spring-boot-autoconfigure/build.gradle
  settings.gradle
  testExamples.sh
Labels: examples

#525 Add Custom NameResolverProvider section to the docs
  docs/en/client/configuration.md
Labels: documentation

#532 Fix GrpcClient#interceptors bean lookup + improve examples
  docs/en/client/configuration.md
  examples/cloud-grpc-client/src/main/java/net/devh/boot/grpc/examples/cloud/client/GlobalClientInterceptorConfiguration.java
  examples/cloud-grpc-server/src/main/java/net/devh/boot/grpc/examples/cloud/server/GlobalInterceptorConfiguration.java
  examples/local-grpc-client/src/main/java/net/devh/boot/grpc/examples/local/client/GlobalClientInterceptorConfiguration.java
  examples/local-grpc-server/src/main/java/net/devh/boot/grpc/examples/local/server/GlobalInterceptorConfiguration.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
  grpc-client-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessorTest.java
Labels: bug

#529 If the grpc client is unavailable then the service is "out of service"
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientHealthAutoConfiguration.java
Labels: bug

#496 Change metadata from gRPC.port to gRPC_port
  docs/en/client/configuration.md
  docs/zh-CN/client/configuration.md
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/nameresolver/DiscoveryClientNameResolver.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/GrpcUtils.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataConsulConfiguration.java
Labels: bug, incompatibility

#528 Make grpc-services.jar optional + remove grpc health service setup
  build.gradle
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcHealthServiceAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcReflectionServiceAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerMetricAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/AbstractGrpcServerFactory.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/GrpcServerFactory.java
  grpc-server-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
  grpc-server-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/server/autoconfigure/AwaitableStreamObserver.java
  grpc-server-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/server/autoconfigure/GrpcHealthServiceDefaultAutoConfigurationTest.java
  grpc-server-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/server/autoconfigure/GrpcHealthServiceFalseAutoConfigurationTest.java
  grpc-server-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/server/autoconfigure/GrpcHealthServiceTrueAutoConfigurationTest.java
  grpc-server-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/server/autoconfigure/GrpcReflectionServiceDefaultAutoConfigurationTest.java
  grpc-server-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/server/autoconfigure/GrpcReflectionServiceFalseAutoConfigurationTest.java
  grpc-server-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/server/autoconfigure/GrpcReflectionServiceTrueAutoConfigurationTest.java
  grpc-server-spring-boot-autoconfigure/src/test/java/net/devh/boot/grpc/server/serverfactory/AbstractGrpcServerFactoryTest.java
  grpc-server-spring-boot-autoconfigure/src/test/resources/logback-test.xml
  tests/src/test/java/net/devh/boot/grpc/test/metric/MetricFullAutoConfigurationTest.java
  tests/src/test/java/net/devh/boot/grpc/test/server/TestServiceImpl.java
  tests/src/test/java/net/devh/boot/grpc/test/shutdown/GrpcServerLifecycleWithCallsTest.java
Labels: bug, cleanup, enhancement
