Repository grpc-ecosystem/grpc-spring, pull requests merged in 2021-09, with the labels that each got.

#579 Fix in docs client configuration examples with server interceptors
  docs/en/client/configuration.md
Labels: documentation

#578 Add logging response messages and other data to ClientLogInterceptor example
  examples/cloud-grpc-client/src/main/java/net/devh/boot/grpc/examples/cloud/client/LogGrpcInterceptor.java
  examples/local-grpc-client/src/main/java/net/devh/boot/grpc/examples/local/client/LogGrpcInterceptor.java
Labels: examples

#580 Extra annotation for gRPC clients/stubs integration with spring context
  docs/en/client/configuration.md
  docs/en/client/getting-started.md
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClient.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBean.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeans.java
  tests/src/test/java/net/devh/boot/grpc/test/inject/GrpcClientBeanInjectionNegativeTest.java
  tests/src/test/java/net/devh/boot/grpc/test/inject/GrpcClientBeanInjectionTest.java
Labels: enhancement

#585 Don't reference sleuth directly in the annotation.
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/autoconfigure/GrpcCommonTraceAutoConfiguration.java
Labels: enhancement, incompatibility

#583 Upgrade GRPC version due to new feature introduced in 1.40.0 version.
  build.gradle
  docs/en/client/configuration.md
  docs/zh-CN/client/configuration.md
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/nameresolver/SelfNameResolverFactory.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/SelfNameResolverConnectionTest.java
Labels: enhancement, feedback required

#523 Colorize different outputs differently for visual disambiguation
  testExamples.sh
Labels: enhancement, examples
