Repository grpc-ecosystem/grpc-spring, pull requests merged in 2022-09, with the labels that each got.

#733 Fix typo
  docs/en/server/testing.md
Labels: documentation

#734 Fix some warnings from code analysis
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/channelfactory/AbstractChannelFactory.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/cloud/package-info.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/authentication/X509CertificateAuthenticationProvider.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/AccessPredicates.java
Labels: cleanup

#735 Update to spring-boot v2.6.11
  build.gradle
  docs/en/versions.md
Labels: dependencies

#738 Fix keystore JKS format auto detection
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/security/KeyStoreUtils.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/SelfSignedMutualJksKeystoreSetupTest.java
  tests/src/test/java/net/devh/boot/grpc/test/setup/SelfSignedMutualP12KeystoreSetupTest.java
  tests/src/test/resources/certificates/client1.jks
  tests/src/test/resources/certificates/client2.jks
  tests/src/test/resources/certificates/generateCertificates.sh
  tests/src/test/resources/certificates/server.jks
  tests/src/test/resources/certificates/trusted-clients.jks
  tests/src/test/resources/certificates/trusted-servers.jks
Labels: bug

#737 Support `@Order` on interceptor bean factory methods
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientTraceAutoConfiguration.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/interceptor/GlobalClientInterceptorRegistry.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/interceptor/OrderedClientInterceptor.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/InterceptorOrder.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerTraceAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/interceptor/GlobalServerInterceptorRegistry.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/interceptor/OrderedServerInterceptor.java
  tests/src/test/java/net/devh/boot/grpc/test/config/AwaitableServerClientCallConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/config/OrderedClientInterceptorConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/config/OrderedServerInterceptorConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/interceptor/DefaultServerInterceptorTest.java
  tests/src/test/java/net/devh/boot/grpc/test/interceptor/OrderedClientInterceptorTest.java
  tests/src/test/java/net/devh/boot/grpc/test/interceptor/OrderedServerInterceptorTest.java
Labels: enhancement

#736 Replace metric implementation with external/official one
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/autoconfigure/GrpcClientMetricAutoConfiguration.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metric/MetricCollectingClientCall.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metric/MetricCollectingClientCallListener.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metric/MetricCollectingClientInterceptor.java
  grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/metric/package-info.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/metric/AbstractMetricCollectingInterceptor.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/metric/MetricConstants.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/metric/MetricUtils.java
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/metric/package-info.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcServerMetricAutoConfiguration.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/MetricCollectingServerCall.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/MetricCollectingServerCallListener.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/MetricCollectingServerInterceptor.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/metric/package-info.java
  tests/src/test/java/net/devh/boot/grpc/test/interceptor/DefaultServerInterceptorTest.java
  tests/src/test/java/net/devh/boot/grpc/test/metric/MetricAutoConfigurationTest.java
  tests/src/test/java/net/devh/boot/grpc/test/metric/MetricCollectingClientInterceptorTest.java
  tests/src/test/java/net/devh/boot/grpc/test/metric/MetricCollectingInterceptorTest.java
  tests/src/test/java/net/devh/boot/grpc/test/metric/MetricCollectingServerInterceptorTest.java
  tests/src/test/java/net/devh/boot/grpc/test/metric/MetricCustomAutoConfigurationTest.java
  tests/src/test/java/net/devh/boot/grpc/test/metric/MetricFullAutoConfigurationTest.java
  tests/src/test/java/net/devh/boot/grpc/test/metric/MetricTestHelper.java
Labels: enhancement, cleanup, dependencies

#742 BREAKING: Add support for call attribute based authorization checks
  docs/en/server/security.md
  docs/zh-CN/server/security.md
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/AbstractGrpcSecurityMetadataSource.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/AccessPredicate.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/AccessPredicateVoter.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/AccessPredicates.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/GrpcSecurityMetadataSource.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/check/ManualGrpcSecurityMetadataSource.java
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/AuthorizationCheckingServerInterceptor.java
  tests/src/test/java/net/devh/boot/grpc/test/config/DualInProcessConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/config/ManualSecurityConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/config/WithBasicAuthSecurityConfiguration.java
  tests/src/test/java/net/devh/boot/grpc/test/security/AbstractSecurityTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/AbstractSecurityWithBasicAuthTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/ManualSecurityWithBasicAuthTest.java
  tests/src/test/java/net/devh/boot/grpc/test/security/ManualSecurityWithCertificateTest.java
Labels: enhancement
