Repository grpc-ecosystem/grpc-spring, pull requests merged in 2022-11, with the labels that each got.

#777 Improve error message if there is no GrpcContext assigned/active
  grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/scope/GrpcRequestScope.java
Labels: enhancement

#786 Prepare release v2.14.0
  build.gradle
  docs/en/versions.md
Labels: release

#787 Fix Kotlin versions being overridden by Spring
  build.gradle
Labels: dependencies
