Repository grpc-ecosystem/grpc-spring, pull requests merged in 2022-05, with the labels that each got.

#659 Update GitHub workflows to use the latest actions versions
  .github/workflows/build-master.yml
  .github/workflows/pull-request.yml
Labels: enhancement

#645 Correct tag names according to Micrometer's docs
  docs/en/actuator.md
  docs/zh-CN/actuator.md
  grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/metric/MetricConstants.java
Labels: enhancement

#666 remove obsolete guice dependency
  grpc-server-spring-boot-autoconfigure/build.gradle
Labels: dependencies

#683 Fix kubernetes config doc
  docs/en/kubernetes.md
Labels: documentation
